In [7]:
using Revise, StatsBase, DataFrames, CSV, QARBoM

In [2]:
df = DataFrame(CSV.File("./tep_normal_train.csv"))

1200×53 DataFrame
  Row │ C1       C2       C3       C4       C5       C6       C7       C8      ⋯
      │ Float64  Float64  Float64  Float64  Float64  Float64  Float64  Float64 ⋯
──────┼─────────────────────────────────────────────────────────────────────────
    1 │   62.92   53.815   24.55    60.741   22.234   40.215   39.663   49.113 ⋯
    2 │   63.24   54.252   24.792   59.78    22.189   40.207   39.064   46.322
    3 │   63.61   53.772   24.62    60.108   22.001   40.346   38.205   49.821
    4 │   63.5    53.881   24.78    62.752   22.101   39.936   43.227   47.4
    5 │   63.44   54.328   24.97    58.28    22.294   38.133   36.967   45.92  ⋯
    6 │   63.38   53.878   24.933   61.113   21.974   38.619   38.901   47.832
    7 │   62.46   54.336   23.749   59.756   22.036   40.935   39.451   47.054
    8 │   62.19   54.243   23.752   60.048   22.216   40.613   37.995   48.332
    9 │   62.73   53.912   20.341   60.957   22.067   39.928   42.971   46.869 ⋯
   10 │   62.39   53.937   20.42    60.777   22.358   39.845   38.979   46.968
   11 │   62.93   54.101   21.053   60.328   21.906   38.285   39.555   43.595
  ⋮   │    ⋮        ⋮        ⋮        ⋮        ⋮        ⋮        ⋮        ⋮    ⋱
 1191 │   62.13   54.149   22.043   60.106   21.56    39.594   35.526   48.475
 1192 │   62.45   54.186   21.874   61.866   21.632   39.8     39.109   46.32  ⋯
 1193 │   63.25   54.31    28.097   61.386   21.315   40.662   39.019   50.057
 1194 │   63.36   54.511   28.394   63.494   21.378   40.501   33.657   45.716
 1195 │   63.59   54.013   31.988   60.648   21.437   39.268   41.878   46.777
 1196 │   63.23   54.348   32.169   61.146   21.412   39.249   34.098   45.637 ⋯
 1197 │   63.53   53.953   26.834   62.095   21.689   40.273   36.531   47.35
 1198 │   63.27   53.699   27.062   59.804   21.665   40.134   37.258   45.883
 1199 │   63.15   53.714   30.706   61.375   21.778   39.255   35.503   46.745
 1200 │   62.95   53.638   30.745   62.277   21.695   38.904   38.838   44.118 ⋯
                                                45 columns and 1179 rows omitted

In [3]:
? fit

search: fit fit! fitted isfitted filter filter! confint first firstindex



Fit a statistical model.

---

```
fit(Histogram, data[, weight][, edges]; closed=:left[, nbins])
```

Fit a histogram to `data`.

# Arguments

  * `data`: either a vector (for a 1-dimensional histogram), or a tuple of vectors of equal length (for an *n*-dimensional histogram).
  * `weight`: an optional `AbstractWeights` (of the same length as the data vectors), denoting the weight each observation contributes to the bin. If no weight vector is supplied, each observation has weight 1.
  * `edges`: a vector (typically an `AbstractRange` object), or tuple of vectors, that gives the edges of the bins along each dimension. If no edges are provided, they are chosen so that approximately `nbins` bins of equal width are constructed along each dimension.

!!! note
    In most cases, the number of bins will be `nbins`. However, to ensure that the bins have equal width, more or fewer than `nbins` bins may be used.


# Keyword arguments

  * `closed`: if `:left` (the default), the bin intervals are left-closed [a,b); if `:right`, intervals are right-closed (a,b].
  * `nbins`: if no `edges` argument is supplied, the approximate number of bins to use along each dimension (can be either a single integer, or a tuple of integers). If omitted, it is computed using Sturges's formula, i.e. `ceil(log2(length(n))) + 1` with `n` the number of data points.

# Examples

```julia
# Univariate
h = fit(Histogram, rand(100))
h = fit(Histogram, rand(100), 0:0.1:1.0)
h = fit(Histogram, rand(100), nbins=10)
h = fit(Histogram, rand(100), weights(rand(100)), 0:0.1:1.0)
h = fit(Histogram, [20], 0:20:100)
h = fit(Histogram, [20], 0:20:100, closed=:right)

# Multivariate
h = fit(Histogram, (rand(100),rand(100)))
h = fit(Histogram, (rand(100),rand(100)),nbins=10)
```

---

```
fit(ZScoreTransform, X; dims=nothing, center=true, scale=true)
```

Fit standardization parameters to vector or matrix `X` and return a `ZScoreTransform` transformation object.

# Keyword arguments

  * `dims`: if `1` fit standardization parameters in column-wise fashion; if `2` fit in row-wise fashion. The default is `nothing`, which is equivalent to `dims=2` with a deprecation warning.
  * `center`: if `true` (the default) center data so that its mean is zero.
  * `scale`: if `true` (the default) scale the data so that its variance is equal to one.

# Examples

```jldoctest
julia> using StatsBase

julia> X = [0.0 -0.5 0.5; 0.0 1.0 2.0]
2×3 Matrix{Float64}:
 0.0  -0.5  0.5
 0.0   1.0  2.0

julia> dt = fit(ZScoreTransform, X, dims=2)
ZScoreTransform{Float64, Vector{Float64}}(2, 2, [0.0, 1.0], [0.5, 1.0])

julia> StatsBase.transform(dt, X)
2×3 Matrix{Float64}:
  0.0  -1.0  1.0
 -1.0   0.0  1.0
```

---

```
fit(UnitRangeTransform, X; dims=nothing, unit=true)
```

Fit a scaling parameters to vector or matrix `X` and return a `UnitRangeTransform` transformation object.

# Keyword arguments

  * `dims`: if `1` fit standardization parameters in column-wise fashion;

if `2` fit in row-wise fashion. The default is `nothing`.

  * `unit`: if `true` (the default) shift the minimum data to zero.

# Examples

```jldoctest
julia> using StatsBase

julia> X = [0.0 -0.5 0.5; 0.0 1.0 2.0]
2×3 Matrix{Float64}:
 0.0  -0.5  0.5
 0.0   1.0  2.0

julia> dt = fit(UnitRangeTransform, X, dims=2)
UnitRangeTransform{Float64, Vector{Float64}}(2, 2, true, [-0.5, 0.0], [1.0, 0.5])

julia> StatsBase.transform(dt, X)
2×3 Matrix{Float64}:
 0.5  0.0  1.0
 0.0  0.5  1.0
```


In [13]:
df_zscore = select(df,All() .=> zscore) 
select!(df_zscore, Not(:C12_zscore))
df_zscore

1200×52 DataFrame
  Row │ C1_zscore   C2_zscore   C3_zscore    C4_zscore   C5_zscore    C6_zscor ⋯
      │ Float64     Float64     Float64      Float64     Float64      Float64  ⋯
──────┼─────────────────────────────────────────────────────────────────────────
    1 │ -0.21751    -0.346618   -0.0296897   -0.448699    0.0212264    0.06324 ⋯
    2 │  0.342977    0.522908    0.0427723   -1.21306    -0.0414842    0.05837
    3 │  0.991039   -0.432178   -0.00872964  -0.952177   -0.303475     0.14294
    4 │  0.798372   -0.215294    0.0391792    1.15082    -0.164118    -0.10650
    5 │  0.693281    0.67413     0.0960709   -2.40614     0.10484     -1.20346 ⋯
    6 │  0.588189   -0.221263    0.084992    -0.152816   -0.341101    -0.90777
    7 │ -1.02321     0.690048   -0.269533    -1.23215    -0.2547       0.50129
    8 │ -1.49612     0.505      -0.268635    -0.9999     -0.00385786   0.30539
    9 │ -0.550298   -0.153611   -1.28999     -0.276896   -0.2115      -0.11136 ⋯
   10 │ -1.14581    -0.103867   -1.26634     -0.420065    0.194029    -0.16186
   11 │ -0.199994    0.222454   -1.0768      -0.777192   -0.435864    -1.11098
  ⋮   │     ⋮           ⋮            ⋮           ⋮            ⋮           ⋮    ⋱
 1191 │ -1.60121     0.317962   -0.780361    -0.953767   -0.918039    -0.31457
 1192 │ -1.04072     0.391583   -0.830965     0.446107   -0.817702    -0.18924 ⋯
 1193 │  0.360492    0.638314    1.03239      0.0643233  -1.25946      0.33520
 1194 │  0.553159    1.03826     1.12132      1.74099    -1.17167      0.23724
 1195 │  0.956009    0.0473547   2.19747     -0.52267    -1.08945     -0.51291
 1196 │  0.325462    0.713925    2.25167     -0.126569   -1.12429     -0.52447 ⋯
 1197 │  0.850917   -0.072031    0.654209     0.62825    -0.738268     0.09853
 1198 │  0.395522   -0.577431    0.722479    -1.19397    -0.771714     0.01396
 1199 │  0.18534    -0.547584    1.8136       0.0555741  -0.614241    -0.52082
 1200 │ -0.164964   -0.698806    1.82528      0.77301    -0.729907    -0.73437 ⋯
                                                47 columns and 1179 rows omitted

In [16]:
x_train = Vector{Vector{Float64}}()

for row in eachrow(df_zscore)
    push!(x_train, collect(row))
end

In [27]:
rbm_pcd = RBM(52,20)

RBM([-1.8593079503091605 1.308302236910344 … 0.15098920227624624 0.15761018947130997; 0.9130295412347337 -0.05801872697554236 … -0.46823285698212275 -0.23914632403209835; … ; 0.03468774325862238 0.8221119509088706 … 1.7294498833156484 0.9512443476901419; -0.28736478538691546 -0.6130192044090992 … 0.26434216907234476 0.3043317611077811], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0  …  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], 52, 20)

In [28]:
mse_pcd = QARBoM.train_pcd!(rbm_pcd, x_train; n_epochs = 100, batch_size = 10, learning_rate = 0.001)

Setting mini-batches
Starting training
|------------------------------------------------------------------------------|
| Epoch |    MSE    | Time (Sample) | Time (Gibbs) | Time (Update) | Total     |
|------------------------------------------------------------------------------|
|     1 |   57.1119 |        0.0051 |       0.0183 |        0.0051 |    0.0286 |
|------------------------------------------------------------------------------|
|------------------------------------------------------------------------------|
| Epoch |    MSE    | Time (Sample) | Time (Gibbs) | Time (Update) | Total     |
|------------------------------------------------------------------------------|
|     2 |   54.2747 |        0.0055 |       0.0144 |        0.0044 |    0.0530 |
|------------------------------------------------------------------------------|
|------------------------------------------------------------------------------|
| Epoch |    MSE    | Time (Sample) | Time (Gibbs) | Time (Update) | T

100-element Vector{Float64}:
 57.1118971122877
 54.274731364568474
 52.20369129384424
 50.717546604908584
 49.62785253485313
 48.81874343284089
 48.21320965456562
 47.72770530402701
 47.37593618440818
 47.11985438269438
 46.91385280759494
 46.76236473608121
 46.64931112719089
  ⋮
 47.05719278775056
 47.05675699514236
 47.058387837117984
 47.068691978351005
 47.09138737793974
 47.04291520129361
 47.004340425876535
 46.98278038908947
 46.98117353845146
 46.98891234039309
 47.0092807641046
 47.0089965110008